services:
  messagerie_db:
    image: postgres
    container_name: messagerie-db
    shm_size: 256mb
    restart: unless-stopped
    environment:
      POSTGRES_DB: messagerie
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5533:5432
    volumes:
      - messagerie_data:/var/lib/postgresql/data

  notification_db:
    image: postgres
    container_name: notification-db
    shm_size: 256mb
    restart: unless-stopped
    environment:
      POSTGRES_DB: notification
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5534:5432
    volumes:
      - notification_data:/var/lib/postgresql/data
  kafka:
    image: 'apache/kafka:4.0.1'
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: 'broker, controller'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'BROKER'
      KAFKA_LISTENERS: 'BROKER://:9092,CONTROLLER://:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'BROKER://kafka:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '0@kafka:9093'
volumes:
  messagerie_data:
  notification_data: