services:
  transactions-db:
    image: postgres:latest
    container_name: companion_transactions_db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - transactions_pgdata:/var/lib/postgresql/data
    networks:
      - companion_network

  transactions-service:
    build: .
    container_name: transactions-service
    depends_on:
      - transactions-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://transactions-db:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_API_KEY: ${STRIPE_API_KEY}

      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - companion_network

volumes:
  transactions_pgdata:

networks:
  companion_network:
    name: companion_network
