name: companion

services:
  transactions-db:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      MAIN_DB : ${MAIN_DB}
      TEST_DB : ${TEST_DB}
    volumes:
      - transactions_pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - companion_network

  transactions-service:
    build: .
    container_name: transactions-service
    depends_on:
      - transactions-db
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      MAIN_DB : ${MAIN_DB}
      TEST_DB : ${TEST_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: transactions-db
      SPRING_PROFILES_ACTIVE: dev

      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - companion_network

volumes:
  transactions_pgdata:

networks:
  companion_network:
    name: companion_network
