spring:
  application:
    name: message
  datasource:
    url: jdbc:postgresql://localhost:5533/messagerie
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  flyway:
    enabled: true
    locations:
    - classpath:db/migration
    user: user
    password: password
springdoc:
  swagger-ui:
    path: /swagger-mes-couilles
  api_docs:
    path: /api-docs