name: ðŸš€ Deploy Keycloak Service to Dokku

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    environment: keycloak
    steps:
      - name: ðŸ§­ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ”‘ Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}

      - name: ðŸš€ Deploy to Dokku
        run: |
          ssh-keyscan -H "$DOKKU_HOST" >> ~/.ssh/known_hosts
          git remote add dokku dokku@$DOKKU_HOST:$DOKKU_APP || true
          git push dokku `git subtree split --prefix $SERVICE_DIR_NAME HEAD`:refs/heads/main --force
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
          DOKKU_APP: ${{ vars.DOKKU_APP }}
          SERVICE_DIR_NAME: ${{ vars.SERVICE_DIR_NAME }}